### ISSUE TITLE
Broken links to releases on CDN

### ISSUE THREAD

**Issue by Boobies** [docbook/xslt20-stylesheets#93]
I would have opened this ticket for the CDN repository but that one doesn't allow for tickets to be issued. At any rate, except for README.md, all the links on this page seem to be broken: http://cdn.docbook.org/xslt2.html

**Comment by ndw** [comment]
Thanks. That's fixed. There is still something seriously wrong in the build process, but I've fixed that part "by hand"

**Comment by Boobies** [comment]
Still missing the latest release (2.0.22) that can be found on Maven. I would also recommend adding an URI for the "current" release.

**Comment by ndw** [comment]
Good points.

**Comment by ndw** [comment]
I've made some progress. I believe it'll be served with https: by tomorrow.

**Comment by Boobies** [comment]
Any word on the "current" URI so we don't need to specify the exact version in our files? :)

**Comment by Boobies** [comment]
Great :) Well, I suppose this ticket can be closed.

**Comment by ndw** [comment]
I think so. The artifact should turn up in Maven as well as quickly as sonatype updates.
